DROP TABLE IF EXISTS
    users,
    friends,
    rating,
    genres,
    films,
    film_genres,
    film_likes ;

CREATE TABLE IF NOT EXISTS users (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(100) NOT NULL,
                                     login VARCHAR(100) NOT NULL,
                                     name VARCHAR(100) NOT NULL,
                                     birthday DATE,
                                     UNIQUE(email, login)
);

CREATE TABLE IF NOT EXISTS friends (
                                       user1_id INTEGER REFERENCES users (id),
                                       user2_id INTEGER REFERENCES users (id),
                                       PRIMARY KEY (user1_id, user2_id)
);

CREATE TABLE IF NOT EXISTS rating (
                                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
                                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     rating_id INTEGER REFERENCES rating (id),
                                     name VARCHAR(100) NOT NULL,
                                     description VARCHAR(200) NOT NULL,
                                     releaseDate DATE,
                                     duration INTEGER,
                                     rate INTEGER
);

CREATE TABLE IF NOT EXISTS film_genres (
                                           genre_id INTEGER REFERENCES genres (id),
                                           film_id INTEGER REFERENCES films (id),
                                           PRIMARY KEY (genre_id, film_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
                                          user_id INTEGER REFERENCES users (id),
                                          film_id INTEGER REFERENCES films (id),
                                          PRIMARY KEY (user_id, film_id)
);